name: 'JIRA Issue Link'
description: 'Comment with a link to the corresponding JIRA issue on pull request'
inputs:
  base-url:
    description: 'The base url for your JIRA site'
    required: true
  issue-prefix:
    description: 'The prefix for your issues, i.e. LOG-1234 => LOG'
    required: true
  github-auth:
    description: 'Temporary github authorization token'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
