name: Link Issue

on:
  pull_request:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run the JIRA link action
      uses: ./
      id: link
      with:
        base-url: 'https://www.google.com'
        issue-prefix: 'LINK'
